site_name: Libretro Docs
repo_name: 'libretro/docs'
repo_url: 'https://github.com/libretro/docs'
edit_uri: 'tree/master/docs'
pages:
  - About: 'index.md'
  - For Users:
    - Downloading, Installing and Updating RetroArch:
      - 'Windows': 'guides/install-windows.md'
      - 'MSVC Runtime Compatibility': 'guides/msvc-runtime-versions.md'
      - 'GNU/Linux': 'guides/install-gnu.md'
      - 'iOS/tvOS': 'guides/install-ios.md'
      - 'Nintendo Switch': 'guides/install-libnx.md'
    - Getting Started:
      - 'Welcome': 'guides/welcome-getting-started.md'
      - 'User Interface': 'guides/navigating.md'
      - 'Input and Controls': 'guides/input-and-controls.md'
      - 'Joypad Auto-Configuration': 'guides/joypad-autoconfiguration.md'
      - 'Installing Cores': 'guides/download-cores.md'
      - 'File Browser': 'guides/file-browser.md'
      - 'Launching Content': 'guides/launch-content.md'
      - 'Importing Content': 'guides/import-content.md'
      - 'Custom Settings': 'guides/overrides.md'
      - 'Directory Configuration': 'guides/change-directories.md'
      - 'Generating Logs': 'guides/generating-retroarch-logs.md'
      - 'Troubleshooting': 'guides/troubleshooting-retroarch.md'
      - 'Command-Line Interface (CLI)': 'guides/cli-intro.md'
    - Quick Guide - Windows: 'guides/windows.md'
    - Core Documentation:
      - Bios information HUB: 'library/bios.md'
      - Getting Started with Arcade Emulation: 'guides/arcade-getting-started.md'
      - Core Compatibility:
        - '3DO': 'library/compatibility/3do.md'
        - 'Atari Jaguar': 'library/compatibility/jaguar.md'
        - 'Atari Lynx': 'library/compatibility/lynx.md'
        - 'Bandai Wonderswan': 'library/compatibility/wswan.md'
        - 'NEC PC-FX': 'library/compatibility/pcfx.md'
        - 'Nintendo DS': 'library/compatibility/ds.md'
        - 'Nintendo Game Boy Advance': 'library/compatibility/gba.md'
        - 'Nintendo Game Boy Color': 'library/compatibility/gbc.md'
        - 'Nintendo NES': 'library/compatibility/nes.md'
        - 'Nintendo SNES': 'library/compatibility/snes.md'
        - 'Sega 32X': 'library/compatibility/32x.md'
        - 'Sega Dreamcast': 'library/compatibility/dc.md'
        - 'Sega Saturn': 'library/compatibility/saturn.md'
        - 'Sony Playstation': 'library/compatibility/psx.md'
      - Amstrad Cores:
        - 'Amstrad - CPC (Caprice32)': 'library/caprice32.md'
        - 'Amstrad - CPC (CrocoDS)': 'library/crocods.md'
      - Arcade Cores:
        - 'Arcade (MAME 2003)': 'library/mame_2003.md'
        - 'Arcade (MAME 2003-Plus)': 'library/mame2003_plus.md'
        - 'Arcade (MAME 2010)': 'library/mame_2010.md'
      - Atari Cores:
        - 'Atari - 2600 (Stella)': 'library/stella.md'
        - 'Atari - 7800 (ProSystem)': 'library/prosystem.md'
        - 'Atari - 5200 (Atari800)': 'library/atari800.md'
        - 'Atari - Jaguar (Virtual Jaguar)': 'library/virtual_jaguar.md'
        - 'Atari - Lynx (Beetle Handy)': 'library/beetle_handy.md'
        - 'Atari - Lynx (Handy)': 'library/handy.md'
        - 'Atari - ST/STE/TT/Falcon (Hatari)': 'library/hatari.md'
      - Game Cores:
        - '2048': 'library/2048.md'
        - 'Cave Story (NXEngine)': 'library/nxengine.md'
        - 'Dinothawr': 'library/dinothawr.md'
        - 'Doom (PrBoom)': 'library/prboom.md'
        - 'Dungeon Crawl Stone Soup': 'library/stone_soup.md'
        - 'Handheld Electronic (GW)': 'library/gw.md'
        - 'Minecraft (Craft)': 'library/craft.md'
        - 'Mr.Boom (Bomberman)': 'library/mr_boom.md'
        - 'Quake 1 (TyrQuake)': 'library/tyrquake.md'
        - 'Rick Dangerous (XRick)': 'library/xrick.md'
        - 'The Powder Toy': 'library/the_powder_toy.md'
        - 'Tomb Raider (OpenLara)': 'library/openlara.md'
      - Internal Cores:
        - 'Dummy Core': 'library/dummy.md'
        - 'Remote RetroPad': 'library/remote_retropad.md'
        - 'Video Processor': 'library/video_processor.md'
      - Media Cores:
        - 'FFmpeg': 'library/ffmpeg.md'
        - 'Game Music Emu': 'library/game_music_emu.md'
        - 'Imageviewer': 'library/imageviewer.md'
        - 'PocketCDG': 'library/pocketcdg.md'
      - Misc Cores:
        - '3D Engine': 'library/3d_engine.md'
        - 'The 3DO Company - 3DO (4DO)': 'library/4do.md'
        - 'ChaiLove': 'library/chailove.md'
        - 'CHIP-8 (Emux CHIP-8)': 'library/emux_chip8.md'
        - 'DOS (DOSBox)': 'library/dosbox.md'
        - 'RPG Maker 2000/2003 (EasyRPG)': 'library/easyrpg.md'
        - 'Mattel - Intellivision (FreeIntv)': 'library/freeintv.md'
        - 'Lua Engine (Lutro)': 'library/lutro.md'
        - 'Microsoft - MSX (fMSX)': 'library/fmsx.md'
        - 'MSX/SVI/ColecoVision/SG-1000 (blueMSX)': 'library/bluemsx.md'
        - 'SNK - Neo Geo Pocket / Color (Beetle NeoPop)': 'library/beetle_neopop.md'
        - 'Magnavox - Odyssey2 / Phillips Videopac+ (O2EM)': 'library/o2em.md'
        - 'Sharp - X68000 (PX68k)': 'library/px68k.md'
        - 'ScummVM': 'library/scummvm.md'
        - 'Thomson - MO/TO (Theodore)': 'library/theodore.md'
        - 'Uzebox (Uzem)': 'library/uzem.md'
        - 'GCE - Vectrex (vecx)': 'library/vecx.md'
        - 'Bandai - WonderSwan/Color (Beetle Cygne)': 'library/beetle_cygne.md'
        - 'ZX Spectrum (Fuse)': 'library/fuse.md'
        - 'Sinclair - ZX 81 (EightyOne)': 'library/eightyone.md'
      - Nintendo Cores:
        - 'Nintendo - Game Boy / Color (Emux GB)': 'library/emux_gb.md'
        - 'Nintendo - Game Boy / Color (Gambatte)': 'library/gambatte.md'
        - 'Nintendo - Game Boy / Color (SameBoy)': 'library/sameboy.md'
        - 'Nintendo - Game Boy / Game Boy Color (TGB Dual)': 'library/tgb_dual.md'
        - 'Nintendo - Game Boy / Color (Gearboy)': 'library/gearboy.md'
        - 'Nintendo - Game Boy Advance (Beetle GBA)': 'library/beetle_gba.md'
        - 'Nintendo - Game Boy Advance (gpSP)': 'library/gpsp.md'
        - 'Nintendo - Game Boy Advance (Meteor)': 'library/meteor.md'
        - 'Nintendo - Game Boy Advance (mGBA)': 'library/mgba.md'
        - 'Nintendo - Game Boy Advance (VBA Next)': 'library/vba_next.md'
        - 'Nintendo - Game Boy Advance (VBA-M)': 'library/vba_m.md'
        - 'Nintendo - GameCube/Wii (Dolphin)': 'library/dolphin.md'
        - 'Nintendo - NES (bnes)': 'library/bnes.md'
        - 'Nintendo - NES / Famicom (Emux NES)': 'library/emux_nes.md'
        - 'Nintendo - NES / Famicom (FCEUmm)': 'library/fceumm.md'
        - 'Nintendo - NES / Famicom (Mesen)': 'library/mesen.md'
        - 'Nintendo - NES / Famicom (Nestopia UE)': 'library/nestopia_ue.md'
        - 'Nintendo - NES / Famicom (QuickNES)': 'library/quicknes.md'
        - 'Nintendo - 3DS (Citra)': 'library/citra.md'
        - 'Nintendo - 3DS (Citra Canary/Experimental)': 'library/citra_canary.md'
        - 'Nintendo - Nintendo 64 (Mupen64Plus)': 'library/mupen64plus.md'
        - 'Nintendo - DS (DeSmuME 2015)': 'library/desmume_2015.md'
        - 'Nintendo - DS (DeSmuME)': 'library/desmume.md'
        - 'Nintendo - DS (melonDS)': 'library/melonds.md'
        - 'Nintendo - Pok√©mon Mini (PokeMini)': 'library/pokemini.md'
        - 'Nintendo - SNES / Famicom (Beetle bsnes)': 'library/beetle_bsnes.md'
        - 'Nintendo - SNES / Famicom (bsnes Accuracy)': 'library/bsnes_accuracy.md'
        - 'Nintendo - SNES / Famicom (bsnes Balanced)': 'library/bsnes_balanced.md'
        - 'Nintendo - SNES / Famicom (bsnes C++98 (v085))': 'library/bsnes_cplusplus98.md'
        - 'Nintendo - SNES / Famicom (bsnes Performance)': 'library/bsnes_performance.md'
        - 'Nintendo - SNES / Famicom (bsnes-mercury Accuracy)': 'library/bsnes_mercury_accuracy.md'
        - 'Nintendo - SNES / Famicom (bsnes-mercury Balanced)': 'library/bsnes_mercury_balanced.md'
        - 'Nintendo - SNES / Famicom (bsnes-mercury Performance)': 'library/bsnes_mercury_performance.md'
        - 'Nintendo - SNES / Famicom (higan Accuracy)': 'library/higan_accuracy.md'
        - 'Nintendo - SNES / Famicom (nSide Balanced)': 'library/nside_balanced.md'
        - 'Nintendo - SNES / Famicom (Snes9x 2002)': 'library/snes9x_2002.md'
        - 'Nintendo - SNES / Famicom (Snes9x 2005 Plus)': 'library/snes9x_2005_plus.md'
        - 'Nintendo - SNES / Famicom (Snes9x 2005)': 'library/snes9x_2005.md'
        - 'Nintendo - SNES / Famicom (Snes9x 2010)': 'library/snes9x_2010.md'
        - 'Nintendo - SNES / Famicom (Snes9x)': 'library/snes9x.md'
        - 'Nintendo - Virtual Boy (Beetle VB)': 'library/beetle_vb.md'
      - NEC Cores:
        - 'NEC - PC-98 (Neko Project II Kai)': 'library/neko_project_ii_kai.md'
        - 'NEC - PC Engine SuperGrafx (Beetle SGX)': 'library/beetle_sgx.md'
        - 'NEC - PC Engine / CD (Beetle PCE FAST)': 'library/beetle_pce_fast.md'
        - 'NEC - PC-FX (Beetle PC-FX)': 'library/beetle_pc_fx.md'
      - Sega Cores:
        - 'Sega - Dreamcast (Redream)': 'library/redream.md'
        - 'Sega - Dreamcast (Reicast)': 'library/reicast.md'
        - 'Sega - Master System (Emux SMS)': 'library/emux_sms.md'
        - 'Sega - MS/GG (Gearsystem)': 'library/gearsystem.md'
        - 'Sega - MS/GG/MD/CD (Genesis Plus GX)': 'library/genesis_plus_gx.md'
        - 'Sega - MS/MD/CD/32X (PicoDrive)': 'library/picodrive.md'
        - 'Sega - Saturn (Beetle Saturn)': 'library/beetle_saturn.md'
        - 'Sega - Saturn (Yabause)': 'library/yabause.md'
        - 'VeMUlator': 'library/vemulator.md'
      - Sony Cores:
        - 'Sony - PlayStation (Beetle PSX)': 'library/beetle_psx.md'
        - 'Sony - PlayStation (Beetle PSX HW)': 'library/beetle_psx_hw.md'
        - 'Sony - PlayStation (PCSX ReARMed)': 'library/pcsx_rearmed.md'
        - 'Sony - PlayStation Portable (PPSSPP)': 'library/ppsspp.md'
    - Feature Specific:
      - 'Cheat/Rumble Codes': 'guides/cheat-codes.md'
      - 'Input and Joypad Drivers': 'guides/input-joypad-drivers.md'
      - 'Linux KMS Mode': 'guides/kms-mode.md'
      - 'Netplay Getting Started / FAQ': 'guides/netplay-faq.md'
      - 'ROMs, Playlists, and Thumbnails': 'guides/roms-playlists-thumbnails.md'
      - 'Run Ahead': 'guides/runahead.md'
      - 'RetroAchievements': 'guides/retroachievements.md'
      - 'Video Recording and Streaming': 'guides/recording-and-streaming.md'
    - Interface Customization:
      - 'Creating a Theme': 'guides/themes.md'
      - 'Libretro Overlays': 'guides/libretro-overlays.md'
      - 'RGUI Interface': 'guides/rgui.md'
    - Advanced Topics:
      - 'Optimal Vsync Performance': 'guides/optimal-vsync.md'
      - 'Softpatching ROMs': 'guides/softpatching.md'
    - Shader Previews:
      - 'Introduction': 'shader/introduction.md'
      - '3dfx': 'shader/3dfx.md'
      - 'antialiasing': 'shader/antialiasing.md'
      - 'border': 'shader/border.md'
      - 'cgp': 'shader/cgp.md'
      - 'crt': 'shader/crt.md'
      - 'crt-royale': 'shader/crt_royale.md'
      - 'cubic': 'shader/cubic.md'
      - 'ddt': 'shader/ddt.md'
      - 'dithering': 'shader/dithering.md'
      - 'eagle': 'shader/eagle.md'
      - 'handheld': 'shader/handheld.md'
      - 'handheld-border': 'shader/handheld-border.md'
      - 'hqx': 'shader/hqx.md'
      - 'linear': 'shader/linear.md'
      - 'motionblur': 'shader/motionblur.md'
      - 'mudlord': 'shader/mudlord.md'
      - 'nedi': 'shader/nedi.md'
      - 'nnedi3': 'shader/nnedi3.md'
      - 'ntsc': 'shader/ntsc.md'
      - 'presets': 'shader/presets.md'
      - 'retro': 'shader/retro.md'
      - 'sabr': 'shader/sabr.md'
      - 'scalefx-OLD-shaders': 'shader/scalefx-old-shaders.md'
      - 'scalefx': 'shader/scalefx.md'
      - 'scalehq': 'shader/scalehq.md'
      - 'scalenx': 'shader/scalenx.md'
      - 'sharpen': 'shader/sharpen.md'
      - 'windowed': 'shader/windowed.md'
      - 'xbr': 'shader/xbr.md'
      - 'xbrz': 'shader/xbrz.md'
      - 'xsal': 'shader/xsal.md'
      - 'xsoft': 'shader/xsoft.md'
  - For Developers:
    - Libretro API and Ecosystem:
      - 'Libretro Overview': 'development/libretro-overview.md'
      - 'Libretro Open Source Bounties': 'development/bounties.md'
      - 'Input API': 'development/input-api.md'
      - 'Libretro Coding Standards': 'development/coding-standards.md'
      - 'Licenses': 'development/licenses.md'
      - 'Libretro Frontends': 'development/frontends.md'
    - RetroArch Development:
      - 'Debugging': 'development/retroarch/debugging.md'
      - 'Adding Menu Entries': 'development/retroarch/new-menu-options.md'
      - 'Input Overlays': 'development/retroarch/overlay.md'
      - 'Adding Translations': 'development/retroarch/new-translations.md'
      - Network Protocols:
        - 'Netplay': 'development/retroarch/netplay.md'
        - 'Network Control Interface': 'development/retroarch/network-control-interface.md'
      - RetroArch Compilation Guides:
        - Apple:
          - 'OSX/PowerPC': 'development/retroarch/compilation/osxppc.md'
          - 'OSX/macOS': 'development/retroarch/compilation/osx.md'
          - 'iOS': 'development/retroarch/compilation/ios.md'
        - 'Android': 'development/retroarch/compilation/android.md'
        - Linux and BSD:
          - 'Overview for Linux/BSD': 'development/retroarch/compilation/linux-and-bsd.md'
          - 'Ubuntu': 'development/retroarch/compilation/ubuntu.md'
        - 'Haiku': 'development/retroarch/compilation/haiku.md'
        - Microsoft:
          - 'DOS': 'development/retroarch/compilation/dos.md'
          - Windows NT3.51 (MSVC6):
            - 'MSVC Commandline': 'development/retroarch/compilation/windowsNT351-msvc-cmdline.md'
          - Windows 95/98/NT4 (MSVC2003):
            - 'MSVC Commandline': 'development/retroarch/compilation/windows95-msvc-cmdline.md'
          - Windows 98SE/ME/2000 (MSVC2005):
            - 'MSVC Commandline': 'development/retroarch/compilation/windows98-msvc-cmdline.md'
            - 'MSVC IDE': 'development/retroarch/compilation/windows98.md'
          - Windows 2000 and later (MSVC2008):
            - 'MSVC Commandline': 'development/retroarch/compilation/windows2000-msvc-cmdline.md'
            - 'MSVC IDE': 'development/retroarch/compilation/windows2000.md'
          - Windows XP and later (MSVC2010):
            - 'MSVC Commandline': 'development/retroarch/compilation/windowsXP-msvc-cmdline.md'
            - 'MSVC IDE': 'development/retroarch/compilation/windowsXP.md'
          - 'Windows 7 and later (MSYS2)': 'development/retroarch/compilation/windows.md'
        - Nintendo:
          - 'Nintendo 3DS': 'development/retroarch/compilation/3ds.md'
          - 'Nintendo GameCube': 'development/retroarch/compilation/gamecube.md'
          - 'Nintendo Wii': 'development/retroarch/compilation/wii.md'
          - 'Nintendo Wii U': 'development/retroarch/compilation/wiiu.md'
          - 'Nintendo Switch (libnx)': 'development/retroarch/compilation/switch-libnx.md'
        - Sony:
          - 'PlayStation2': 'development/retroarch/compilation/ps2.md'
          - 'PlayStation Portable': 'development/retroarch/compilation/psp.md'
          - 'PlayStation Vita/TV': 'development/retroarch/compilation/psvita.md'
    - Core Development:
      - 'Core Development Overview': 'development/cores/developing-cores.md'
      - 'Dynamic Rate Control for Emulators': 'development/cores/dynamic-rate-control.md'
      - 'OpenGL Accelerated Cores': 'development/cores/opengl-cores.md'
      - Core-Specific Development Docs:
        - 'Nintendo - GameCube/Wii (Dolphin)': 'development/cores/core-specific/dolphin.md'
        - 'Nintendo - GameCube/Wii (Ishiiruka)': 'development/cores/core-specific/ishiiruka.md'
        - 'MAME (0.181-current)': 'development/cores/core-specific/mame-2016.md'
        - 'MAME 2016': 'development/cores/core-specific/mame.md'
        - 'MAME 2003-Plus': 'development/cores/core-specific/mame-2003-plus.md'
    - Shader Development:
      - 'Shader Development Overview': 'development/shader/shader-overview.md'
      - 'Slang Shader Development': 'development/shader/slang-shaders.md'
      - 'GLSL Shader Development': 'development/shader/glsl-shaders.md'
      - 'Cg Shader Development (deprecated)': 'development/shader/cg-shaders.md'
      - 'XML Shader Development (discontinued)': 'development/shader/xml-shaders.md'
      - 'Content-Aware Shaders': 'development/shader/content-aware-shaders.md'
      - 'Shader Lookup Textures': 'development/shader/shader-lookup-textures.md'
  - Contribute to the Docs:
    - 'Contributing to the Libretro Docs': 'meta/how-to-contribute.md'
    - 'Core List': 'meta/core-list.md'
    - 'Core Template': 'meta/core-template.md'
    - 'Shader Preview Template': 'meta/shader-preview-template.md'
    - 'See Also': 'meta/see-also.md'
extra:
  version: '0.1.0'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  i18n:
    prev: 'Previous'
    next: 'Next'
  palette:
    primary: 'blue'
    accent:  'blue'
theme:
  name: 'material'
  logo: 'image/branding/invader.png'
  favicon: 'image/branding/invader.png'
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      linenums: true
  - markdown.extensions.nl2br
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
