site_name: Libretro Docs
repo_name: 'libretro/docs'
repo_url: 'https://github.com/libretro/docs'
edit_uri: 'tree/master/docs'
pages:
  - About: 'index.md'
  - For Developers:
    - Compilation:
      - Apple:
        - 'OSX/PowerPC': 'compilation/osxppc.md'
        - 'OSX/macOS': 'compilation/osx.md'
        - 'iOS': 'compilation/ios.md'
      - 'Android': 'compilation/android.md'
      - Linux and BSD:
        - 'Overview for Linux/BSD': 'compilation/linux-and-bsd.md'
        - 'Ubuntu': 'compilation/ubuntu.md'
      - 'Haiku': 'compilation/haiku.md'
      - Microsoft:
        - 'DOS': 'compilation/dos.md'
        - Windows NT3.51:
          - 'MSVC Commandline': 'compilation/windowsNT351-msvc-cmdline.md'
        - Windows 95/98/NT4:
          - 'MSVC Commandline': 'compilation/windows95-msvc-cmdline.md'
        - Windows 98SE/ME/2000:
          - 'MSVC Commandline': 'compilation/windows98-msvc-cmdline.md'
          - 'MSVC IDE': 'compilation/windows98.md'
        - Windows XP and later:
          - 'MSVC Commandline': 'compilation/windowsXP-msvc-cmdline.md'
          - 'MSVC IDE': 'compilation/windowsXP.md'
        - 'Windows Vista and later (MSYS2)': 'compilation/windows.md'
      - Nintendo:
        - 'Nintendo 3DS': 'compilation/3ds.md'
        - 'Nintendo GameCube': 'compilation/gamecube.md'
        - 'Nintendo Wii': 'compilation/wii.md'
        - 'Nintendo Wii U': 'compilation/wiiu.md'
      - Sony:
        - 'PlayStation Portable': 'compilation/psp.md'
        - 'PlayStation Vita/TV': 'compilation/psvita.md'
    - Meta:
      - 'Core List': 'meta/core_list.md'
      - 'To Do': 'meta/todo.md'
      - 'Core Template': 'meta/core_template.md'
      - 'See Also': 'meta/see_also.md'
    - Technical:
      - 'Debugging': 'tech/debugging.md'
      - 'Adding Menu Entries': 'tech/new-menu-options.md'
      - 'Licenses': 'tech/licenses.md'
      - 'MSVC Runtimes': 'tech/msvc-runtime-versions.md'
      - 'Adding Translations': 'tech/new-translations.md'
      - Protocols:
        - 'Netplay': 'tech/netplay.md'
        - 'Network Control Interface': 'tech/network-control-interface.md'
      - Specifications:
        - 'Libretro': 'specs/api.md'
        - 'RetroPad': 'specs/retropad.md'
        - 'Shaders': 'specs/shader.md'
        - 'Overlays': 'specs/overlay.md'
  - For Users:
    - Core Documentation:
      - Core Compatibility:
        - '3DO': 'library/compatibility/3do.md'
        - 'Atari Jaguar': 'library/compatibility/jaguar.md'
        - 'Atari Lynx': 'library/compatibility/lynx.md'
        - 'Bandai Wonderswan': 'library/compatibility/wswan.md'
        - 'NEC PC-FX': 'library/compatibility/pcfx.md'
        - 'Nintendo DS': 'library/compatibility/ds.md'
        - 'Nintendo Game Boy Advance': 'library/compatibility/gba.md'
        - 'Nintendo Game Boy Color': 'library/compatibility/gbc.md'
        - 'Nintendo NES': 'library/compatibility/nes.md'
        - 'Nintendo SNES': 'library/compatibility/snes.md'        
        - 'Sega 32X': 'library/compatibility/32x.md'
        - 'Sega Dreamcast': 'library/compatibility/dc.md'
        - 'Sega Saturn': 'library/compatibility/saturn.md'
        - 'Sony Playstation': 'library/compatibility/psx.md'
      - Amstrad Cores:
        - 'Amstrad - CPC (Caprice32)': 'library/caprice32.md'
        - 'Amstrad - CPC (CrocoDS)': 'library/crocods.md'
      - Atari Cores:      
        - 'Atari - 2600 (Stella)': 'library/stella.md'
        - 'Atari - 7800 (ProSystem)': 'library/prosystem.md'
        - 'Atari - 5200 (Atari800)': 'library/atari800.md'
        - 'Atari - Jaguar (Virtual Jaguar)': 'library/virtual_jaguar.md'
        - 'Atari - Lynx (Beetle Handy)': 'library/beetle_handy.md'
        - 'Atari - Lynx (Handy)': 'library/handy.md'
        - 'Atari - ST/STE/TT/Falcon (Hatari)': 'library/hatari.md'
      - Game Cores:
        - '2048': 'library/2048.md'
        - 'Cave Story (NXEngine)': 'library/nxengine.md'
        - 'Dinothawr': 'library/dinothawr.md'
        - 'Doom (PrBoom)': 'library/prboom.md'
        - 'Handheld Electronic (GW)': 'library/gw.md'
        - 'Minecraft (Craft)': 'library/craft.md'
        - 'Mr.Boom (Bomberman)': 'library/mr_boom.md'
        - 'Quake 1 (TyrQuake)': 'library/tyrquake.md'
        - 'Rick Dangerous (XRick)': 'library/xrick.md'
        - 'The Powder Toy': 'library/the_powder_toy.md'
        - 'Tomb Raider (OpenLara)': 'library/openlara.md'
      - Internal Cores:
        - 'Dummy Core': 'library/dummy.md'
        - 'Remote RetroPad': 'library/remote_retropad.md'
        - 'Video Processor': 'library/video_processor.md'
      - Media Cores:
        - 'FFmpeg': 'library/ffmpeg.md'
        - 'Game Music Emu': 'library/game_music_emu.md'
        - 'Imageviewer': 'library/imageviewer.md'
        - 'PocketCDG': 'library/pocketcdg.md'
      - Multi System Cores:
        - 'Arcade (MAME 2003)': 'library/mame_2003.md'
      - Misc Cores:
        - '3D Engine': 'library/3d_engine.md'
        - 'The 3DO Company - 3DO (4DO)': 'library/4do.md'
        - 'ChaiLove': 'library/chailove.md'
        - 'CHIP-8 (Emux CHIP-8)': 'library/emux_chip8.md'
        - 'DOS (DOSBox)': 'library/dosbox.md'
        - 'RPG Maker 2000/2003 (EasyRPG)': 'library/easyrpg.md'
        - 'Mattel - Intellivision (FreeIntv)': 'library/freeintv.md'
        - 'Lua Engine (Lutro)': 'library/lutro.md'
        - 'Microsoft - MSX (fMSX)': 'library/fmsx.md'
        - 'MSX/SVI/ColecoVision/SG-1000 (blueMSX)': 'library/bluemsx.md'
        - 'SNK - Neo Geo Pocket / Color (Beetle NeoPop)': 'library/beetle_neopop.md'
        - 'Magnavox - Odyssey2 / Phillips Videopac+ (O2EM)': 'library/o2em.md'
        - 'Sharp - X68000 (PX68k)': 'library/px68k.md'
        - 'ScummVM': 'library/scummvm.md'
        - 'Uzebox (Uzem)': 'library/uzem.md'
        - 'GCE - Vectrex (vecx)': 'library/vecx.md'
        - 'Bandai - WonderSwan/Color (Beetle Cygne)': 'library/beetle_cygne.md'
        - 'ZX Spectrum (Fuse)': 'library/fuse.md'
        - 'Sinclair - ZX 81 (EightyOne)': 'library/eightyone.md'
      - Nintendo Cores:
        - 'Nintendo - Game Boy / Color (Emux GB)': 'library/emux_gb.md'
        - 'Nintendo - Game Boy / Color (Gambatte)': 'library/gambatte.md'
        - 'Nintendo - Game Boy / Color (SameBoy)': 'library/sameboy.md'
        - 'Nintendo - Game Boy / Game Boy Color (TGB Dual)': 'library/tgb_dual.md'
        - 'Nintendo - Game Boy / Color (Gearboy)': 'library/gearboy.md'
        - 'Nintendo - Game Boy Advance (Beetle GBA)': 'library/beetle_gba.md'
        - 'Nintendo - Game Boy Advance (gpSP)': 'library/gpsp.md'
        - 'Nintendo - Game Boy Advance (Meteor)': 'library/meteor.md'
        - 'Nintendo - Game Boy Advance (mGBA)': 'library/mgba.md'
        - 'Nintendo - Game Boy Advance (VBA Next)': 'library/vba_next.md'
        - 'Nintendo - Game Boy Advance (VBA-M)': 'library/vba_m.md'
        - 'Nintendo - NES (bnes)': 'library/bnes.md'
        - 'Nintendo - NES / Famicom (Emux NES)': 'library/emux_nes.md'
        - 'Nintendo - NES / Famicom (FCEUmm)': 'library/fceumm.md'
        - 'Nintendo - NES / Famicom (Mesen)': 'library/mesen.md'
        - 'Nintendo - NES / Famicom (Nestopia UE)': 'library/nestopia_ue.md'
        - 'Nintendo - NES / Famicom (QuickNES)': 'library/quicknes.md'
        - 'Nintendo - 3DS (Citra)': 'library/citra.md'
        - 'Nintendo - Nintendo 64 (Mupen64Plus)': 'library/mupen64plus.md'
        - 'Nintendo - DS (DeSmuME 2015)': 'library/desmume_2015.md'
        - 'Nintendo - DS (DeSmuME)': 'library/desmume.md'
        - 'Nintendo - DS (melonDS)': 'library/melonds.md'
        - 'Nintendo - Pok√©mon Mini (PokeMini)': 'library/pokemini.md'
        - 'Nintendo - SNES / Famicom (Beetle bsnes)': 'library/beetle_bsnes.md'
        - 'Nintendo - SNES / Famicom (bsnes Accuracy)': 'library/bsnes_accuracy.md'
        - 'Nintendo - SNES / Famicom (bsnes Balanced)': 'library/bsnes_balanced.md'
        - 'Nintendo - SNES / Famicom (bsnes C++98 (v085))': 'library/bsnes_cplusplus98.md'
        - 'Nintendo - SNES / Famicom (bsnes Performance)': 'library/bsnes_performance.md'
        - 'Nintendo - SNES / Famicom (bsnes-mercury Accuracy)': 'library/bsnes_mercury_accuracy.md'
        - 'Nintendo - SNES / Famicom (bsnes-mercury Balanced)': 'library/bsnes_mercury_balanced.md'
        - 'Nintendo - SNES / Famicom (bsnes-mercury Performance)': 'library/bsnes_mercury_performance.md'
        - 'Nintendo - SNES / Famicom (higan Accuracy)': 'library/higan_accuracy.md'
        - 'Nintendo - SNES / Famicom (nSide Balanced)': 'library/nside_balanced.md'
        - 'Nintendo - SNES / Famicom (Snes9x 2002)': 'library/snes9x_2002.md'
        - 'Nintendo - SNES / Famicom (Snes9x 2005 Plus)': 'library/snes9x_2005_plus.md'
        - 'Nintendo - SNES / Famicom (Snes9x 2005)': 'library/snes9x_2005.md'
        - 'Nintendo - SNES / Famicom (Snes9x 2010)': 'library/snes9x_2010.md'
        - 'Nintendo - SNES / Famicom (Snes9x)': 'library/snes9x.md'
        - 'Nintendo - Virtual Boy (Beetle VB)': 'library/beetle_vb.md'
      - NEC Cores:
        - 'NEC - PC-98 (Neko Project II Kai)': 'library/neko_project_ii_kai.md'
        - 'NEC - PC Engine SuperGrafx (Beetle SGX)': 'library/beetle_sgx.md'
        - 'NEC - PC Engine / CD (Beetle PCE FAST)': 'library/beetle_pce_fast.md'
        - 'NEC - PC-FX (Beetle PC-FX)': 'library/beetle_pc_fx.md'
      - Sega Cores:
        - 'Sega - Dreamcast (Redream)': 'library/redream.md'
        - 'Sega - Dreamcast (Reicast)': 'library/reicast.md'
        - 'Sega - Master System (Emux SMS)': 'library/emux_sms.md'
        - 'Sega - MS/GG/MD/CD (Genesis Plus GX)': 'library/genesis_plus_gx.md'
        - 'Sega - MS/MD/CD/32X (PicoDrive)': 'library/picodrive.md'
        - 'Sega - Saturn (Beetle Saturn)': 'library/beetle_saturn.md'
        - 'Sega - Saturn (Yabause)': 'library/yabause.md'
        - 'VeMUlator': 'library/vemulator.md'
      - Sony Cores:
        - 'Sony - PlayStation (Beetle PSX)': 'library/beetle_psx.md'
        - 'Sony - PlayStation (Beetle PSX HW)': 'library/beetle_psx_hw.md'
        - 'Sony - PlayStation (PCSX ReARMed)': 'library/pcsx_rearmed.md'
        - 'Sony - PlayStation Portable (PPSSPP)': 'library/ppsspp.md'
    - Shader Previews:
      - 'Introduction': 'shader/introduction.md'
      - '3dfx': 'shader/3dfx.md'
      - 'antialiasing': 'shader/antialiasing.md'
      - 'border': 'shader/border.md'
      - 'cgp': 'shader/cgp.md'
      - 'crt': 'shader/crt.md'
      - 'cubic': 'shader/cubic.md'
      - 'ddt': 'shader/ddt.md'
      - 'dithering': 'shader/dithering.md'
      - 'eagle': 'shader/eagle.md'
      - 'handheld': 'shader/handheld.md'
      - 'handheld-border': 'shader/handheld-border.md'
      - 'hqx': 'shader/hqx.md'
      - 'linear': 'shader/linear.md'
      - 'motionblur': 'shader/motionblur.md'
      - 'mudlord': 'shader/mudlord.md'
      - 'nedi': 'shader/nedi.md'
      - 'nnedi3': 'shader/nnedi3.md'
      - 'ntsc': 'shader/ntsc.md'
      - 'presets': 'shader/presets.md'
      - 'retro': 'shader/retro.md'
      - 'sabr': 'shader/sabr.md'
      - 'scalefx-OLD-shaders': 'shader/scalefx-old-shaders.md'
      - 'scalefx': 'shader/scalefx.md'
      - 'scalehq': 'shader/scalehq.md'
      - 'scalenx': 'shader/scalenx.md'
      - 'sharpen': 'shader/sharpen.md'
      - 'windowed': 'shader/windowed.md'
      - 'xbr': 'shader/xbr.md'
      - 'xbrz': 'shader/xbrz.md'
      - 'xsal': 'shader/xsal.md'
      - 'xsoft': 'shader/xsoft.md'
    - Installing and Updating RetroArch:
      - 'Windows': 'guides/install-windows.md'
    - Getting Started:
      - 'Keyboard Controls': 'guides/retroarch-keyboard-controls.md'
      - 'Windows': 'guides/windows.md'
      - 'Command-line interface (CLI)': 'guides/cli-intro.md'
      - 'Generating Logs': 'guides/generating-retroarch-logs.md'
      - 'Troubleshooting': 'guides/troubleshooting-retroarch.md'
    - Interface Customization:
      - 'Creating a Theme': 'guides/themes.md'
      - 'RGUI Interface': 'guides/rgui.md'
    - Feature Specific:
      - 'Input and Joypad Drivers': 'guides/input-joypad-drivers.md'
      - 'Linux KMS Mode': 'guides/kms-mode.md'
      - 'Netplay Getting Started / FAQ': 'guides/netplay-faq.md'
      - 'ROMs, Playlists, and Thumbnails': 'guides/roms-playlists-thumbnails.md'
      - 'RetroAchievements': 'guides/retroachievements.md'
      - 'Video Recording and Streaming': 'guides/recording-and-streaming.md'
    - Advanced Topics:
      - 'Libretro Frontends': 'tech/frontends.md'
      - 'Custom Settings': 'guides/overrides.md'
      - 'Optimal Vsync Performance': 'guides/optimal-vsync.md'
      - 'Softpatching ROMs': 'guides/softpatching.md'
    - Contributing:
      - 'How to Contribute to the Docs': 'guides/how-to-contribute.md'
extra:
  version: '0.1.0'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  i18n:
    prev: 'Previous'
    next: 'Next'
  palette:
    primary: 'blue'
    accent:  'blue'
theme:
  name: 'material'
  logo: 'image/branding/invader.png'
  favicon: 'image/branding/invader.png'
markdown_extensions:
  - admonition
  - codehilite(linenums=true)
  - toc(permalink=Link)
  - pymdownx.details
  - pymdownx.superfences
